### PR TITLE
 Adding support for labels.

### PR DESCRIPTION
**Pull request by danik9**
(Forgive me as im not the best coder lol)

But I wanted to add the ablility to label hex codes or icao numbers in the "watchlist.txt"
and have the labels be sent into telegram.

the structure for the watchlist.txt stays mostly the same but now it should look like this: "a88bde: Dept of Commerce"

all that needs to be added to send a label is adding ": " at the end of an icao or hex.

_also added some extra squawk codes_

this is pretty crude but gets the job done! but it may need some tweaking (again pretty new to coding) so please look over this code before merging!

### CODE REVIEW

**Comment by TheCommsChannel** [comment]
All good! I'm not the best either, lol. I was trying to get this to work but had issues when adding multiple things in the watchlist file. I tested it out and this works great! Thanks for the contribution to the project!

**Comment by cowboy898** [comment]
Dan,
Don't apologize you did a great job with that script. Sometimes we just need to tweak them a little.

Sent using myEarthLink

On Mon Nov 20 18:57:17 CST 2023 Dan wrote:

(Forgive me as im not the best coder lol)

But I wanted to add the ablility to label hex codes or icao numbers in the "watchlist.txt"
and have the labels be sent into telegram.

the structure for the watchlist.txt stays mostly the same but now it should look like this: "a88bde: Dept of Commerce"

all that needs to be added to send a label is adding ": " at the end of an icao or hex.

also added some extra squawk codes

this is pretty crude but gets the job done! but it way need some tweaking (again pretty new to coding) so please look over this code before merging!

You can view, comment on, or merge this pull request online at:

https://github.com/TheCommsChannel/SkyWatch/pull/1

Commit Summary
e5447ea (https://github.com/TheCommsChannel/SkyWatch/pull/1/commits/e5447ea5a3f1edf38cd347476d4cbaad3f70ea18) Adding support for labels.
aac6423 (https://github.com/TheCommsChannel/SkyWatch/pull/1/commits/aac64231b42bce14802e96a7d7d764d949f99132) Delete .DS_Store

File Changes

(2 files (https://github.com/TheCommsChannel/SkyWatch/pull/1/files))

M

skywatch.py (http://skywatch.py)

(14)
M watchlist.txt (https://github.com/TheCommsChannel/SkyWatch/pull/1/files#diff-ca8b20a3bb43a2d81744ab79fde4b00fbc0279b97a3b5836a0741fa21f4a9762) (2)

Patch Links:

https://github.com/TheCommsChannel/SkyWatch/pull/1.patch

https://github.com/TheCommsChannel/SkyWatch/pull/1.diff

**Comment by danik9** [comment]
> en adding mu

Glad to hear!

**Comment by danik9** [comment]
> All good! I'm not the best either, lol. I was trying to get this to work but had issues when adding multiple things in the watchlist file. I tested it out and this works great! Thanks for the contribution to the project!

Glad to Hear!

**Comment by danik9** [comment]
> Dan, Don't apologize you did a great job with that script. Sometimes we just need to tweak them a little.>

thanks!

**Comment by cowboy898** [comment]
No problem.

Can you show me the line that you changed so I can make the update manually?


Their first mistake was thinking I was one of the Sheep.
-----Original Message-----

**Comment by danik9** [comment]
> No problem.
> 
> Can you show me the line that you changed so I can make the update manually?
> 

Sure thing. But id recommend looking here to see the changes https://github.com/TheCommsChannel/SkyWatch/pull/1/commits/e5447ea5a3f1edf38cd347476d4cbaad3f70ea18 The main things that were added were:

Replace the def load_ watchlist with this:

def load_watchlist():
    watchlist = {}
    with open("watchlist.txt", "r") as file:
        for line in file:
            parts = line.split(':', 1)
            if len(parts) == 2:
                hex_code = parts[0].strip().upper()
                label = parts[1].strip()
                watchlist[hex_code] = label
    return watchlist

Then in the watchlist alert section add the this code under f"Hex: {hex_code}\n": 

f"Label: {watchlist[entry]}\n"


So it would be

f"Hex: {hex_code}\n"
f"Label: {watchlist[entry]}\n"

This is kinda a rough explanation so it would be best to check out that link.

**Pull request merged**
